<?php

/*
 * Based on: https://drupalize.me/blog/201502/write-hello-world-test-drupal-7-simpletest
 */

function helloworld_menu() {

  $items = array();
  $items['helloworld'] = array(
    'title' => 'Hello World',
    'access callback' => TRUE,
    'page callback' => 'helloworld_page',
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  );

  return $items;
}

function helloworld_page() {
    $p = drupal_get_path('module', 'helloworld');

    drupal_add_css('http://fonts.googleapis.com/css?family=Indie+Flower', array('group' => CSS_THEME, 'type' => 'external'));
    drupal_add_css($p . '/css/helloworld.css');
    drupal_add_js($p . '/js/helloworld.js');

    return '<p id="hello"></p>';
}

